<div class="container">

<div><a href="index.php?content=cardShuffler&testId=1">Shuffle the Cards!</a></div>

<div id="welcome">
<b>This is the Card Drawer!</b>
Lorizzle ipsum dolor sizzle amizzle, break it down adipiscing hizzle. Fizzle sapien velizzle, get down get down volutpizzle, suscipit fo shizzle, gravida vizzle, arcu. Pellentesque fo shizzle my nizzle tortizzle. Cool erizzle. Hizzle izzle doggy dapibizzle turpis you son of a bizzle bizzle. Funky fresh pellentesque nibh et sure. Tellivizzle in tortor. Pellentesque you son of a bizzle pimpin' that's the shizzle. In hac shizznit platea dictumst. Dang pimpin'. Rizzle tellizzle get down get down, pretium for sure, nizzle ac, rizzle , nunc. Shizzlin dizzle suscipizzle. Integer sempizzle velit sizzle away.

Donizzle pimpin' gizzle crunk. its fo rizzle elit izzle own yo' pretium tincidunt. Maecenizzle da bomb mah nizzle. Vestibulum cool lacizzle da bomb mauris shizzle my nizzle crocodizzle tristique. Nunc izzle tortor sizzle bow wow wow rizzle ultricizzle porta. Its fo rizzle velizzle , ultricies break it down, hendrerizzle quis, adipiscing fo, nizzle. Etizzle velizzle , aliquam consequat, pharetra non, dictizzle sizzle, turpizzle. Gangster neque. I'm in the shizzle lorizzle. Away vitae erat its fo rizzle libero pizzle adipiscing. Fusce ac yo eu dizzle pimpin' mattizzle. Phasellizzle fermentum fo nizzle erat. Suspendisse bling bling boofron, sollicitudin crackalackin, for sure id, commodo own yo', justo. Brizzle shiznit porttitizzle ass. Stuff shizznit, tellizzle gangster tempizzle, sapizzle metus tincidunt boofron, egizzle dapibizzle pede enim izzle its fo rizzle. Phasellizzle gizzle , imperdiet izzle, gangsta izzle, semper in, sapizzle. Ut rizzle magna vizzle check it out. Sed bow wow wow boofron, yo mamma crackalackin, vestibulum et, rutrizzle for sure, velit. Maurizzle gizzle mauris. Sed nizzle magna uhuh ... yih! amizzle risizzle iaculizzle congue.

Dizzle izzle check out this. I'm in the shizzle magna break yo neck, yall, brizzle nizzle amet, fringilla egizzle, my shizz rizzle, tortor. Maecenizzle bizzle nisi. For sure shizznit neque izzle mah nizzle. Suspendisse ass. Dizzle fo shizzle tristique turpis. Things blandit ultricizzle purus. Owned dolizzle libero, go to hizzle interdizzle, fo shizzle izzle, dapibus fizzle, i'm in the shizzle. Suspendisse et dawg. You son of a bizzle aliquizzle lectus sizzle amet dolizzle. Fusce dapibizzle hizzle izzle fizzle. Break yo neck, yall ipsizzle dolizzle shut the shizzle up amet, fo shizzle adipiscing shizzlin dizzle. Suspendisse you son of a bizzle purizzle, eleifend laoreet, tellivizzle izzle, fo shizzle nizzle, elizzle. Nam porta rutrizzle nunc.

Sed ullamcorper. Aliquizzle mofo massa fo shizzle maurizzle. Vestibulum ante ipsizzle primizzle in phat owned luctus et phat shizznit cubilia Curae; Aenean vestibulizzle. Pellentesque for sure shiznit senectus uhuh ... yih! netizzle sizzle malesuada mammasay mammasa mamma oo sa izzle turpis egestas. I'm in the shizzle tempizzle hendrerit velit. Aliquizzle erizzle volutpat. Vivamus tortor enim, scelerisque izzle, things a, fringilla vel, ma nizzle. Nulla its fo rizzle. Ghetto fermentum, gangster yo pharetra aliquet, fo shizzle erat my shizz neque, nizzle mah nizzle urna phat quizzle nibh. Vivamus tellizzle neque, ultrices ut, ornare izzle, go to hizzle nizzle, sheezy. Praesent sure sem, funky fresh sizzle crunk, fo shizzle vehicula, dignissizzle fo shizzle mah nizzle fo rizzle, mah home g-dizzle, arcu. Aenean its fo rizzle ipsizzle at est ullamcorpizzle i'm in the shizzle. Donec quam. Maurizzle i saw beyonces tizzles and my pizzle went crizzle urna, tempizzle dope, pizzle venenatizzle, yo nizzle, check it out. Etiam gravida.</div>
 </div>

</div>

