<div class="container">

<div id="welcome"><b>You are Logged In!  </b>It's a beautiful day in this neighborhood a beautiful day for a neighbor. Would you be mine? Could you be mine? Its a neighborly day in this beautywood a neighborly day for a beauty. Would you be mine? Could you be mine. The movie star the professor and Mary Ann here on Gilligans Isle. So lets make the most of this beautiful day. Since we're together Space. The final frontier. These are the voyages of the Starship Enterprise. That this group would somehow form a family that's the way we all became the Brady Bunch. Wouldn't you like to get away? Sometimes you want to go where everybody knows your name. And they're always glad you came! Come and dance on our floor. Take a step that is new. We've a loveable space that needs your face threes company too. So get a witch's shawl on a broomstick you can crawl on. Were gonna pay a call on the Addams Family. Go Speed Racer. Go Speed Racer. Go Speed Racer go! No phone no lights no motor car not a single luxury. Like Robinson Crusoe it's primitive as can be.

Well the first thing you know ol' Jeds a millionaire. Kinfolk said Jed move away from there. Said Californ'y is the place you ought to be So they loaded up the truck and moved to Beverly. Hills that is. Swimmin' pools movie stars. Go Speed Racer. Go Speed Racer. Go Speed Racer go!, Maybe you and me were never meant to be. But baby think of me once in awhile. I'm at WKRP in Cincinnati. Fish don't fry in the kitchen and beans don't burn on the grill. Took a whole lotta tryin' just to get up that hill? And if you threw a party - invited everyone you knew. You would see the biggest gift would be from me and the card attached would say thank you for being a friend. Well we're movin' on up to the east side to a deluxe apartment in the sky. Didn't need no welfare states. Everybody pulled his weight. Gee our old Lasalle ran great. Those were the days. Space. The final frontier. These are the voyages of the Starship Enterprise. Said Californ'y is the place you ought to be So they loaded up the truck and moved to Beverly. Hills that is. Swimmin' pools movie stars.

They call him Flipper Flipper faster than lightning. No one you see is smarter than he. The first mate and his Skipper too will do their very best to make the others comfortable in their tropic island nest? I have always wanted to have a neighbor just like you. I've always wanted to live in a neighborhood with you! So get a witch's shawl on a broomstick you can crawl on. Were gonna pay a call on the Addams Family. Texas tea. Doin' it our way. Nothin's gonna turn us back now. Straight ahead and on the track now. We're gonna make our dreams come true. Movin' on up to the east side. We finally got a piece of the pie. Doin' it our way. There's nothing we wont try. Never heard the word impossible. This time there's no stopping us. It's time to play the music. It's time to light the lights. It's time to meet the Muppets on the Muppet Show tonight. Come and listen to a story about a man named Jed - a poor mountaineer barely kept his family fed?

They're creepy and they're kooky mysterious and spooky. They're all together ooky the Addams Family. They were four men living all together yet they were all alone. Space. The final frontier. These are the voyages of the Starship Enterprise.

Fleeing from the Cylon tyranny the last Battlestar – Galactica - leads a rag-tag fugitive fleet on a lonely quest - a shining planet known as Earth. One two three four five six seven eight Sclemeel schlemazel hasenfeffer incorporated.

</div>